# Generated by Django 5.2.11 on 2026-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_trip_user_alter_usermedia_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trip',
            name='sql_trip_user_id_a1330b_idx',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user_id', '-created_at'], name='sql_trip_user_id_a1330b_idx'),
        ),
    ]
