# Generated by Django 5.2.11 on 2026-02-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_trip_sql_trip_user_id_a1330b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usermedia',
            name='sql_user_me_user_id_44bd6d_idx',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='user',
        ),
        migrations.AddField(
            model_name='usermedia',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AddIndex(
            model_name='usermedia',
            index=models.Index(fields=['user_id', '-uploaded_at'], name='sql_user_me_user_id_44bd6d_idx'),
        ),
    ]
