# Generated by Django 4.2.27 on 2026-02-08 16:48

from django.db import migrations
import team4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team4', '0002_amenity_created_at_amenity_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='location',
            field=team4.fields.PointField(blank=True, null=True, verbose_name='موقعیت جغرافیایی مرکز'),
        ),
    ]
